# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cirrent' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cirrent
  	pod 'SDWebImage'
  	pod 'JGProgressHUD'

  	pod 'ActionCell', '~> 2.0.0'
  	pod 'IQKeyboardManagerSwift'
end
