# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SamsungARTIK' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
pod 'AFNetworking', '3.0'
pod 'ReachabilitySwift', '~> 3'
pod 'ArtikCloud', :git => 'https://github.com/vaibhav3002/artikcloud-objc.git'
pod 'Fabric'
pod 'Crashlytics'
pod 'SwiftKeychainWrapper'
pod 'Toaster', '~> 2.0'
pod "KCFloatingActionButton", "~> 2.2.0"
pod 'JGProgressHUD'
pod 'SDWebImage'

# Pods for SamsungARTIK

target 'SamsungARTIKTests' do
inherit! :search_paths
# Pods for testing
end

target 'SamsungARTIKUITests' do
inherit! :search_paths
# Pods for testing
end

end
